# Generated by Django 6.0.3 on 2026-04-03 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_articles', to='news_app1.publisher'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='articles',
            field=models.ManyToManyField(related_name='included_in_newsletters', to='news_app1.article'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_newsletters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribed_journalists',
            field=models.ManyToManyField(blank=True, related_name='journalist_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribed_publishers',
            field=models.ManyToManyField(blank=True, related_name='reader_subscribers', to='news_app1.publisher'),
        ),
    ]
