# Generated by Django 6.0.3 on 2026-04-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app1', '0002_alter_article_publisher_alter_newsletter_articles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Reader', 'Reader'), ('Journalist', 'Journalist'), ('Editor', 'Editor')], max_length=20),
        ),
    ]
