# Generated by Django 6.0.3 on 2026-04-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app1', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
