# Generated by Django 6.0.3 on 2026-04-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app1', '0004_article_review_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
